export const CHATBOT_SUGGESTED_QUESTIONS = [
  'What value does CyfroAI Insights provide?',
  'What are some of the core benefits of CyfroSec?',
  'What does Service Fingerprinting do?',
  'What are some of the Dashboard visualisations which can be handy for executives?',
  'What is the executive summary generated by CyfroAI Engine?',
  'How often does CyfroSec scan for vulnerabilities?',
  'What would be the content of Reports?',
] as const;

const CHATBOT_RESPONSES = {
  aiInsights:
    'It accelerates your response with easily understandable AI-powered remediation guidance and correlation which can be understood from management executives to security engineers.\n\nIt helps in context-aware prioritization to focus on the issues that actually pose risk.\n\nFrequent scans flood teams with thousands of low value alerts, burying the impacting issues that actually need immediate action.',
  benefits:
    'CyfroAI Engine helps in generating insights and remediation guidelines which can be easily understood by executives as well as security engineers.\n\nReduces time to detect with continuous scans and AI Insights.\n\nReduces time to fix with prioritised findings and remediation steps.\n\nReduces risk with risk scores and GDPR Compliance tool.\n\nImproves audit readiness with exportable compliance ready report of scans.',
  fingerprinting:
    'It helps in uncovering system vulnerabilities, misconfigurations and secrets.\n\nEach finding includes a clear description and evidence like file, package details or command output would be provided.\n\nActionable remediation steps like upgrades, configuration change or credential rotation.',
  dashboard:
    'The Dashboard is your central view of the security health of your infrastructure.\n\nIt brings together scan status, vulnerability findings, agent health, asset discovery, GDPR compliance, and AI-generated insights into a single page.\n\nThe dashboards are customisable and they update dynamically when you switch between account groups as well.',
  executiveSummary:
    'It is an easily understandable natural language overview of the most important security findings along with correlation.\n\nVulnerabilities are re-ranked using exposure correlation, not just CVSS severity alone.\n\nIt prevents impacting issues from getting buried since they are the ones which actually need immediate action.',
  scan: 'You can schedule scans to run automatically for every 1, 6, 12 or 24 hours depending on your usecase.',
  reports:
    'Provides an unified, auditable record of discovery, open ports/services, fingerprints, vulnerabilities, misconfigurations, and secrets found during scans.\n\nThe scan results can be filtered using data ranges and the various other data fields available for easy viewing.\n\nA structured CSV file can also be downloaded for deeper analysis. The CSV file would contain the results of all the scans in different sheets.',
  default: 'I can help you with information about CyfroSec. Click any question below to get started.',
} as const;

export function getChatbotResponse(text: string) {
  const lower = text.toLowerCase();

  if (lower.includes('ai insights') || lower.includes('cyfro ai insights')) {
    return CHATBOT_RESPONSES.aiInsights;
  }
  if (lower.includes('core benefits') || lower.includes('benefits of cyfrosec')) {
    return CHATBOT_RESPONSES.benefits;
  }
  if (lower.includes('service fingerprinting') || lower.includes('fingerprinting')) {
    return CHATBOT_RESPONSES.fingerprinting;
  }
  if (lower.includes('dashboard') || lower.includes('visualisation') || lower.includes('executive')) {
    return CHATBOT_RESPONSES.dashboard;
  }
  if (lower.includes('executive summary') || lower.includes('ai engine')) {
    return CHATBOT_RESPONSES.executiveSummary;
  }
  if (
    lower.includes('how often') ||
    lower.includes('scan for') ||
    lower.includes('frequency') ||
    lower.includes('vulnerabilities')
  ) {
    return CHATBOT_RESPONSES.scan;
  }
  if (lower.includes('report')) {
    return CHATBOT_RESPONSES.reports;
  }

  return CHATBOT_RESPONSES.default;
}
